// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Club struct {
	Nombre string `json:"nombre"`
	Ciudad string `json:"ciudad"`
}

type Jugador struct {
	Nombre          string    `json:"nombre"`
	IDJugador       int32     `json:"id_jugador"`
	Posicion        string    `json:"posicion"`
	Edad            int32     `json:"edad"`
	FechaNacimiento time.Time `json:"fecha_nacimiento"`
	Altura          string    `json:"altura"`
	PaisNombre      string    `json:"pais_nombre"`
}

type Jugo struct {
	FechaInicio      time.Time `json:"fecha_inicio"`
	FechaFin         time.Time `json:"fecha_fin"`
	JugadorNombre    string    `json:"jugador_nombre"`
	JugadorIDJugador int32     `json:"jugador_id_jugador"`
	ClubNombre       string    `json:"club_nombre"`
	ClubCiudad       string    `json:"club_ciudad"`
}

type Lesion struct {
	TipoLesion  string `json:"tipo_lesion"`
	Descripcion string `json:"descripcion"`
}

type Pai struct {
	Nombre string `json:"nombre"`
}

type Tiene struct {
	FechaInicio      time.Time `json:"fecha_inicio"`
	FechaFin         time.Time `json:"fecha_fin"`
	JugadorNombre    string    `json:"jugador_nombre"`
	JugadorIDJugador int32     `json:"jugador_id_jugador"`
	LesionTipoLesion string    `json:"lesion_tipo_lesion"`
}
