// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Jugador struct {
	Nombre          string    `json:"nombre"`
	IDJugador       int32     `json:"id_jugador"`
	Posicion        string    `json:"posicion"`
	FechaNacimiento time.Time `json:"fecha_nacimiento"`
	Altura          int32     `json:"altura"`
	PaisNombre      string    `json:"pais_nombre"`
}

type Pai struct {
	Nombre string `json:"nombre"`
}
