// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createJugador = `-- name: CreateJugador :one
INSERT INTO Jugador (Nombre, iD_Jugador, Posicion,Fecha_Nacimiento, Altura, Pais_Nombre)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING Nombre, iD_Jugador, Posicion,Fecha_Nacimiento, Altura, Pais_Nombre
`

type CreateJugadorParams struct {
	Nombre          string    `json:"nombre"`
	IDJugador       int32     `json:"id_jugador"`
	Posicion        string    `json:"posicion"`
	FechaNacimiento time.Time `json:"fecha_nacimiento"`
	Altura          int32     `json:"altura"`
	PaisNombre      string    `json:"pais_nombre"`
}

func (q *Queries) CreateJugador(ctx context.Context, arg CreateJugadorParams) (Jugador, error) {
	row := q.db.QueryRowContext(ctx, createJugador,
		arg.Nombre,
		arg.IDJugador,
		arg.Posicion,
		arg.FechaNacimiento,
		arg.Altura,
		arg.PaisNombre,
	)
	var i Jugador
	err := row.Scan(
		&i.Nombre,
		&i.IDJugador,
		&i.Posicion,
		&i.FechaNacimiento,
		&i.Altura,
		&i.PaisNombre,
	)
	return i, err
}

const createPais = `-- name: CreatePais :one
INSERT INTO Pais(Nombre)
VALUES ($1)
RETURNING Nombre
`

func (q *Queries) CreatePais(ctx context.Context, nombre string) (string, error) {
	row := q.db.QueryRowContext(ctx, createPais, nombre)
	err := row.Scan(&nombre)
	return nombre, err
}

const deleteJugador = `-- name: DeleteJugador :exec
DELETE FROM Jugador
WHERE iD_Jugador = $1
`

func (q *Queries) DeleteJugador(ctx context.Context, idJugador int32) error {
	_, err := q.db.ExecContext(ctx, deleteJugador, idJugador)
	return err
}

const deletePais = `-- name: DeletePais :exec
DELETE FROM Pais
WHERE Nombre = $1
`

func (q *Queries) DeletePais(ctx context.Context, nombre string) error {
	_, err := q.db.ExecContext(ctx, deletePais, nombre)
	return err
}

const getJugador = `-- name: GetJugador :one
SELECT nombre, id_jugador, posicion, fecha_nacimiento, altura, pais_nombre FROM Jugador
WHERE iD_Jugador = $1
`

func (q *Queries) GetJugador(ctx context.Context, idJugador int32) (Jugador, error) {
	row := q.db.QueryRowContext(ctx, getJugador, idJugador)
	var i Jugador
	err := row.Scan(
		&i.Nombre,
		&i.IDJugador,
		&i.Posicion,
		&i.FechaNacimiento,
		&i.Altura,
		&i.PaisNombre,
	)
	return i, err
}

const getPais = `-- name: GetPais :one
SELECT nombre FROM Pais
WHERE Nombre = $1
`

func (q *Queries) GetPais(ctx context.Context, nombre string) (string, error) {
	row := q.db.QueryRowContext(ctx, getPais, nombre)
	err := row.Scan(&nombre)
	return nombre, err
}

const listJugadores = `-- name: ListJugadores :many
SELECT iD_Jugador, Nombre FROM Jugador
ORDER BY iD_Jugador
`

type ListJugadoresRow struct {
	IDJugador int32  `json:"id_jugador"`
	Nombre    string `json:"nombre"`
}

func (q *Queries) ListJugadores(ctx context.Context) ([]ListJugadoresRow, error) {
	rows, err := q.db.QueryContext(ctx, listJugadores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJugadoresRow
	for rows.Next() {
		var i ListJugadoresRow
		if err := rows.Scan(&i.IDJugador, &i.Nombre); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaises = `-- name: ListPaises :many
SELECT nombre FROM Pais
`

func (q *Queries) ListPaises(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPaises)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var nombre string
		if err := rows.Scan(&nombre); err != nil {
			return nil, err
		}
		items = append(items, nombre)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlantel = `-- name: ListPlantel :many
SELECT nombre, id_jugador, posicion, fecha_nacimiento, altura, pais_nombre FROM Jugador
ORDER BY 
  CASE Posicion
    WHEN 'Arquero' THEN 1
    WHEN 'Defensor' THEN 2
    WHEN 'Mediocampista' THEN 3
    WHEN 'Delantero' THEN 4
    ELSE 5
  END,
  iD_Jugador
`

func (q *Queries) ListPlantel(ctx context.Context) ([]Jugador, error) {
	rows, err := q.db.QueryContext(ctx, listPlantel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Jugador
	for rows.Next() {
		var i Jugador
		if err := rows.Scan(
			&i.Nombre,
			&i.IDJugador,
			&i.Posicion,
			&i.FechaNacimiento,
			&i.Altura,
			&i.PaisNombre,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJugador = `-- name: UpdateJugador :exec
UPDATE Jugador
SET Nombre = $1, Posicion = $2, Fecha_Nacimiento = $3, Altura = $4, Pais_Nombre = $5
WHERE iD_Jugador = $6
`

type UpdateJugadorParams struct {
	Nombre          string    `json:"nombre"`
	Posicion        string    `json:"posicion"`
	FechaNacimiento time.Time `json:"fecha_nacimiento"`
	Altura          int32     `json:"altura"`
	PaisNombre      string    `json:"pais_nombre"`
	IDJugador       int32     `json:"id_jugador"`
}

func (q *Queries) UpdateJugador(ctx context.Context, arg UpdateJugadorParams) error {
	_, err := q.db.ExecContext(ctx, updateJugador,
		arg.Nombre,
		arg.Posicion,
		arg.FechaNacimiento,
		arg.Altura,
		arg.PaisNombre,
		arg.IDJugador,
	)
	return err
}

const updatePais = `-- name: UpdatePais :exec
UPDATE Pais
SET Nombre = $1
WHERE Nombre = $2
`

type UpdatePaisParams struct {
	Nombre   string `json:"nombre"`
	Nombre_2 string `json:"nombre_2"`
}

func (q *Queries) UpdatePais(ctx context.Context, arg UpdatePaisParams) error {
	_, err := q.db.ExecContext(ctx, updatePais, arg.Nombre, arg.Nombre_2)
	return err
}
